/* Bilingual copy for the PraxisAI marketing site (from the rebranding brief).
   FR is primary; EN is the secondary translation.
   NOTE: the `services` array is intentionally kept verbatim from the prior site —
   per the brief, the services offering is not changed in this rebrand. */
window.SITE_CONTENT = {
  fr: {
    brand: 'PraxisAI',
    tagline: 'L’IA pratique au service de la transformation organisationnelle.',
    cta: 'Planifier un appel',
    nav: [
      { id: 'services', label: 'Services' },
      { id: 'approche', label: 'Approche' },
      { id: 'industries', label: 'Industries' },
      { id: 'apropos', label: 'À propos' },
      { id: 'perspectives', label: 'Perspectives' },
    ],
    hero: {
      eyebrow: 'Intelligence artificielle organisationnelle',
      title: 'L’IA pratique au service de la transformation organisationnelle',
      sub: "PraxisAI aide les organisations à passer de la curiosité envers l’IA à des capacités concrètes, des pratiques responsables et des impacts mesurables.",
      primary: 'Planifier un appel',
      ghost: 'Découvrir nos services',
    },
    why: {
      eyebrow: 'Problématique',
      title: 'Le potentiel de l’IA est clair. Le défi est de le mettre en pratique.',
      body: "De nombreuses organisations expérimentent l’IA, mais peinent à l’intégrer dans leurs opérations, leurs processus et leurs décisions. Nous vous aidons à combler l’écart entre le potentiel et l’impact réel — avec méthode, rigueur et pragmatisme.",
    },
    servicesPreview: { eyebrow: 'Nos services', title: 'Nos services', intro: "Comment nous vous aidons à transformer avec l’IA — de la formation à l’implémentation." },
    services: [
      { icon: 'graduation-cap', title: 'Formation IA',
        tagline: "Former vos équipes à travailler avec l'IA",
        desc: "Des programmes de formation sur mesure pour chaque niveau de votre organisation — dirigeants, gestionnaires, employés. Initiations à l'IA, ateliers pratiques, formations aux outils. Nous construisons le plan adapté à votre contexte et à vos objectifs.",
        items: ["Introduction à l'IA", 'Outils IA pratiques', 'Ateliers sur mesure', 'Formation pour dirigeants', 'Formation pour gestionnaires', 'Formation pour employés'] },
      { icon: 'scan-search', title: 'Diagnostic organisationnel',
        tagline: "Identifier où l'IA peut vraiment faire la différence",
        desc: "Nous nous asseyons avec vous, observons vos processus de bout en bout, et identifions les opportunités concrètes d'automatisation et d'intégration IA. Vous repartez avec des recommandations personnalisées : outils adaptés, idées de transformation, plan de formation et feuille de route.",
        items: ['Cartographie des processus', "Opportunités d'automatisation", "Recommandations d'outils IA", 'Plan de formation', 'Feuille de route stratégique', 'Recommandations opérationnelles'] },
      { icon: 'rocket', title: 'Implémentation',
        tagline: 'De la stratégie à la réalité',
        desc: "Au-delà du conseil, nous passons à l'action. Déploiement d'outils d'automatisation, d'agents IA et de systèmes agentiques, exécution des plans de formation, intégration dans vos systèmes existants. Nous exécutons ce que nous recommandons.",
        items: ['Automatisation des processus', 'Agents IA', 'Systèmes agentiques', 'Déploiement de formation', 'Intégration système', 'Accompagnement continu'] },
    ],
    whyUs: {
      eyebrow: 'Pourquoi PraxisAI',
      title: 'Pourquoi les organisations choisissent PraxisAI',
      cards: [
        { title: 'Expertise bilingue', desc: "Une équipe qui travaille en français et en anglais, au plus près de votre réalité organisationnelle." },
        { title: 'Rigueur académique', desc: "Une démarche fondée sur la recherche et des méthodes éprouvées — jamais sur l’effet de mode." },
        { title: 'Expérience industrielle', desc: "Une connaissance concrète du terrain, acquise dans plusieurs secteurs d’activité." },
        { title: 'IA pratique et responsable', desc: "Des recommandations applicables et mesurables, déployées de façon responsable et durable." },
        { title: 'Du potentiel à l’impact', desc: "Nous ne nous arrêtons pas à la stratégie — nous formons, intégrons et exécutons jusqu’aux résultats." },
      ],
    },
    methodology: {
      eyebrow: 'Notre approche',
      title: 'Une approche pratique de la transformation IA',
      intro: "Nous combinons formation, stratégie, expertise technique et expérience terrain pour développer des capacités IA qui créent de la valeur dans toute votre organisation.",
      steps: [
        { step: '01', title: 'Définir', desc: 'Nous clarifions vos objectifs, vos processus et les cas d’usage à plus fort potentiel.' },
        { step: '02', title: 'Diagnostiquer', desc: "Nous évaluons votre maturité IA et identifions des opportunités concrètes et applicables." },
        { step: '03', title: 'Développer', desc: "Nous concevons un plan sur mesure : formation, stratégie et choix technologiques." },
        { step: '04', title: 'Déployer', desc: "Nous passons à l’exécution et mesurons l’impact réel sur vos opérations." },
      ],
    },
    values: {
      eyebrow: 'Voix de marque',
      title: 'Ce qui guide chacune de nos interventions',
      items: [
        { icon: 'target', title: 'Pratique', desc: 'Nous nous concentrons sur des applications réelles et des résultats tangibles.' },
        { icon: 'compass', title: 'Stratégique', desc: 'Nous relions l’IA aux objectifs d’affaires et à l’impact organisationnel.' },
        { icon: 'users', title: 'Humain', desc: 'Nous plaçons les personnes au centre et respectons le facteur humain.' },
        { icon: 'shield-check', title: 'Crédible', desc: 'Nous apportons expertise, rigueur et responsabilité.' },
        { icon: 'feather', title: 'Clair', desc: 'Nous communiquons simplement et efficacement.' },
      ],
    },
    industries: {
      eyebrow: 'Secteurs',
      title: 'Secteurs que nous accompagnons',
      intro: "Une expérience concrète, au service de chaque réalité organisationnelle.",
      list: ['PME', 'Services professionnels', 'Secteur public', 'Éducation', 'Organismes à but non lucratif', 'Opérations industrielles', 'Santé', 'Environnement & Développement durable'],
    },
    about: {
      eyebrow: 'À propos',
      title: 'Notre mission',
      intro: [
        "PraxisAI aide les organisations à transformer le potentiel de l’intelligence artificielle en capacités concrètes, en processus plus intelligents et en pratiques responsables.",
        "Nous rendons l’IA pratique, stratégique et actionnable pour les organisations.",
        "Nous accompagnons les organisations à chaque étape de leur parcours IA : de la sensibilisation et la formation jusqu’à l’intégration stratégique, la collaboration technique et l’accompagnement expert.",
      ],
      teamTitle: 'Une équipe multidisciplinaire',
      teamBody: "PraxisAI réunit des expertises complémentaires en intelligence artificielle, en stratégie, en formation et en transformation organisationnelle.",
      areas: ['Formation & littératie IA', 'Diagnostic organisationnel', 'Intégration & conseil IA', 'Collaboration technique', 'Stratégie d’affaires', 'Gestion du changement', 'Transformation numérique', 'Optimisation des processus', 'Gouvernance de l’IA', 'Intégration système'],
      core: "PraxisAI ne mise pas sur l’effet de mode autour de l’IA. Notre rôle est de transformer l’IA en pratiques organisationnelles structurées — concrètes, mesurables et durables.",
    },
    insights: {
      eyebrow: 'Perspectives',
      title: 'Perspectives',
      note: 'Contenu exemple — à remplacer.',
      articles: [
        { tag: 'Stratégie', date: 'Mars 2026', title: "Cinq questions à poser avant de lancer un projet IA", excerpt: 'Un cadre simple pour évaluer la maturité IA de votre organisation avant tout investissement.' },
        { tag: 'Pratique', date: 'Février 2026', title: "Du potentiel à la pratique : intégrer l’IA dans vos opérations", excerpt: "Comment passer de l’expérimentation ponctuelle à des capacités durables." },
        { tag: 'Gouvernance', date: 'Janvier 2026', title: "Adopter l’IA de façon responsable", excerpt: "Les principes d’une intégration mesurable, responsable et alignée sur vos valeurs." },
      ],
      readMore: "Lire l’article →",
    },
    contact: {
      eyebrow: 'Travaillons ensemble',
      title: 'Prêt à faire fonctionner l’IA dans votre organisation ?',
      support: "Discutons de vos défis et de vos opportunités, et de la façon dont nous pouvons bâtir des capacités IA concrètes, ensemble.",
      fields: { name: 'Nom', org: 'Organisation', email: 'Courriel', phone: 'Téléphone', message: 'Message' },
      placeholders: { name: 'Votre nom', org: 'Votre organisation', email: 'vous@exemple.com', phone: '+1 …', message: 'Votre message' },
      submit: 'Planifier un appel',
      success: 'Merci — nous vous répondrons sous peu.',
      errRequired: 'Ce champ est requis.',
      errEmail: 'Adresse courriel invalide.',
    },
    statement: "PraxisAI aide les organisations à passer du potentiel de l’IA à des capacités concrètes, des pratiques responsables et des impacts mesurables.",
    finalCta: { title: 'Prêt à faire fonctionner l’IA dans votre organisation ?', sub: "Planifions un premier appel pour explorer ce que nous pouvons bâtir, ensemble." },
    footer: {
      services: { title: 'Services', items: ['Formation & littératie IA', 'Intégration & conseil IA', 'Collaboration technique', 'Conférences & ateliers'] },
      resources: { title: 'Ressources', items: ['Perspectives', 'Événements', 'Études de cas', 'Blogue'] },
      contactTitle: 'Contact',
      contactLine: 'Bâtissons ensemble des capacités IA concrètes.',
    },
  },

  en: {
    brand: 'PraxisAI',
    tagline: 'Practical AI for organizational transformation.',
    cta: 'Book a call',
    nav: [
      { id: 'services', label: 'Services' },
      { id: 'approche', label: 'Approach' },
      { id: 'industries', label: 'Industries' },
      { id: 'apropos', label: 'About' },
      { id: 'perspectives', label: 'Insights' },
    ],
    hero: {
      eyebrow: 'Organizational AI',
      title: 'Practical AI for organizational transformation',
      sub: "PraxisAI helps organizations move from AI curiosity to concrete capabilities, responsible practices, and measurable impact.",
      primary: 'Book a call',
      ghost: 'Discover our services',
    },
    why: {
      eyebrow: 'The challenge',
      title: 'AI potential is clear. Turning it into practice is the challenge.',
      body: "Many organizations experiment with AI, but struggle to integrate it into daily operations, processes, and decisions. We help you bridge the gap between potential and real-world impact — with method, rigor, and pragmatism.",
    },
    servicesPreview: { eyebrow: 'Our services', title: 'Our Services', intro: 'How we help you transform with AI — from training to implementation.' },
    services: [
      { icon: 'graduation-cap', title: 'AI Training',
        tagline: 'Equip your teams to work with AI',
        desc: 'Custom training programs for every level of your organization — executives, managers, employees. AI fundamentals, hands-on workshops, tool-specific training. We build the program that fits your context and your goals.',
        items: ['AI Fundamentals', 'Practical AI Tools', 'Custom Workshops', 'Executive Training', 'Manager Training', 'Employee Training'] },
      { icon: 'scan-search', title: 'Organizational Diagnostic',
        tagline: 'Identify where AI can make a real difference',
        desc: 'We sit with you, observe your end-to-end processes, and identify concrete automation and AI integration opportunities. You leave with personalized recommendations: adapted tools, transformation ideas, training plan, and a roadmap.',
        items: ['Process Mapping', 'Automation Opportunities', 'AI Tool Recommendations', 'Training Plan', 'Strategic Roadmap', 'Operational Recommendations'] },
      { icon: 'rocket', title: 'Implementation',
        tagline: 'From Strategy to Reality',
        desc: 'Beyond consulting, we execute. Deploying automation tools, AI agents, and agentic systems, running training programs, integrating into your existing systems. We implement what we recommend.',
        items: ['Process Automation', 'AI Agents', 'Agentic Systems', 'Training Deployment', 'System Integration', 'Ongoing Support'] },
    ],
    whyUs: {
      eyebrow: 'Why PraxisAI',
      title: 'Why organizations choose PraxisAI',
      cards: [
        { title: 'Bilingual expertise', desc: 'A team that works in both French and English, close to your organizational reality.' },
        { title: 'Academic rigor', desc: 'An approach grounded in research and proven methods — never hype.' },
        { title: 'Industry experience', desc: 'Concrete, hands-on knowledge gained across multiple sectors.' },
        { title: 'Practical, responsible AI', desc: 'Applicable, measurable recommendations, deployed responsibly and sustainably.' },
        { title: 'From potential to impact', desc: 'We don’t stop at strategy — we train, integrate, and execute through to results.' },
      ],
    },
    methodology: {
      eyebrow: 'Our approach',
      title: 'A practical approach to AI transformation',
      intro: 'We combine training, strategy, technical expertise, and real-world experience to build AI capabilities that create value across your organization.',
      steps: [
        { step: '01', title: 'Define', desc: 'We clarify your goals, processes, and the highest-potential use cases.' },
        { step: '02', title: 'Diagnose', desc: 'We assess your AI maturity and identify concrete, applicable opportunities.' },
        { step: '03', title: 'Develop', desc: 'We build a tailored plan: training, strategy, and technology choices.' },
        { step: '04', title: 'Deploy', desc: 'We move to execution and measure real impact on your operations.' },
      ],
    },
    values: {
      eyebrow: 'Brand voice',
      title: 'What guides every engagement',
      items: [
        { icon: 'target', title: 'Practical', desc: 'We focus on real applications and tangible outcomes.' },
        { icon: 'compass', title: 'Strategic', desc: 'We connect AI to business goals and organizational impact.' },
        { icon: 'users', title: 'Human', desc: 'We empower people and respect the human factor.' },
        { icon: 'shield-check', title: 'Credible', desc: 'We bring expertise, rigor, and responsibility.' },
        { icon: 'feather', title: 'Clear', desc: 'We communicate simply and effectively.' },
      ],
    },
    industries: {
      eyebrow: 'Sectors',
      title: 'Industries We Serve',
      intro: 'Concrete experience, in service of every organizational reality.',
      list: ['SMEs', 'Professional Services', 'Public Sector', 'Education', 'Non-Profit Organizations', 'Industrial Operations', 'Healthcare', 'Environment & Sustainability'],
    },
    about: {
      eyebrow: 'About',
      title: 'Our mission',
      intro: [
        'PraxisAI helps organizations transform the potential of artificial intelligence into concrete capabilities, smarter processes, and responsible practices.',
        'We make AI practical, strategic, and actionable for organizations.',
        'We support organizations at every stage of their AI journey: from awareness and training to strategic integration, technical collaboration, and expert guidance.',
      ],
      teamTitle: 'A Multidisciplinary Team',
      teamBody: 'PraxisAI brings together complementary expertise in artificial intelligence, strategy, training, and organizational transformation.',
      areas: ['AI Training & Literacy', 'Organizational Diagnostic', 'AI Integration & Advisory', 'Technical Collaboration', 'Business Strategy', 'Change Management', 'Digital Transformation', 'Process Optimization', 'AI Governance', 'System Integration'],
      core: 'PraxisAI is not about AI hype. Our role is to turn AI into structured organizational practice — concrete, measurable, and lasting.',
    },
    insights: {
      eyebrow: 'Insights',
      title: 'Insights',
      note: 'Sample content — to be replaced.',
      articles: [
        { tag: 'Strategy', date: 'March 2026', title: 'Five questions to ask before launching an AI project', excerpt: 'A simple framework to assess your organization’s AI maturity before any investment.' },
        { tag: 'Practice', date: 'February 2026', title: 'From potential to practice: integrating AI into your operations', excerpt: 'How to move from one-off experiments to durable capabilities.' },
        { tag: 'Governance', date: 'January 2026', title: 'Adopting AI responsibly', excerpt: 'The principles of measurable, responsible AI integration aligned with your values.' },
      ],
      readMore: 'Read the article →',
    },
    contact: {
      eyebrow: 'Let’s work together',
      title: 'Ready to make AI work for your organization?',
      support: 'Let’s discuss your challenges and opportunities, and how we can build practical AI capabilities together.',
      fields: { name: 'Name', org: 'Organization', email: 'Email', phone: 'Phone', message: 'Message' },
      placeholders: { name: 'Your name', org: 'Your organization', email: 'you@example.com', phone: '+1 …', message: 'Your message' },
      submit: 'Book a call',
      success: 'Thank you — we’ll be in touch shortly.',
      errRequired: 'This field is required.',
      errEmail: 'Invalid email address.',
    },
    statement: 'PraxisAI helps organizations move from AI potential to concrete capabilities, responsible practices, and measurable impact.',
    finalCta: { title: 'Ready to make AI work for your organization?', sub: 'Let’s book a first call to explore what we can build, together.' },
    footer: {
      services: { title: 'Services', items: ['Training & AI Literacy', 'AI Integration & Advisory', 'Technical Project Collaboration', 'Expert Talks & Keynotes'] },
      resources: { title: 'Resources', items: ['Insights', 'Events', 'Case Studies', 'Blog'] },
      contactTitle: 'Contact',
      contactLine: 'Let’s build practical AI capabilities together.',
    },
  },
};
