/* Bilingual copy for the Humexa marketing site (verbatim from the rebranding brief).
   FR is primary; EN is the secondary translation. The "↔" in "Human ↔ IA / AI"
   is rendered as-is. */
window.SITE_CONTENT = {
  fr: {
    brand: 'Humexa',
    cta: 'Planifier une rencontre',
    nav: [
      { id: 'services', label: 'Services' },
      { id: 'approche', label: 'Approche' },
      { id: 'industries', label: 'Industries' },
      { id: 'apropos', label: 'À propos' },
      { id: 'perspectives', label: 'Perspectives' },
    ],
    hero: {
      eyebrow: 'Human ↔ IA',
      title: 'La transformation IA, bâtie autour de l’humain',
      sub: "L'IA n'est pas là pour remplacer vos équipes. Elle est là pour les amplifier. Nous construisons le lien entre vos collaborateurs et l'intelligence artificielle — à travers la formation, le diagnostic et l'implémentation — pour que chaque personne dans votre organisation en tire pleinement parti.",
      primary: 'Démarrer avec nous',
      ghost: 'Découvrir nos services',
    },
    why: {
      eyebrow: 'Pourquoi maintenant',
      title: 'Pourquoi Human ↔ IA ?',
      body: "L'IA ne devrait pas faire peur. Elle devrait créer des opportunités. Les organisations qui prospèrent ne sont pas celles qui ont remplacé leurs équipes — ce sont celles qui ont su connecter leurs collaborateurs à l'intelligence artificielle : pour automatiser les tâches répétitives, prendre de meilleures décisions et créer de nouveaux rôles. La question n'est plus « faut-il adopter l'IA ? » — c'est « comment la faire travailler avec vos équipes ? »",
    },
    servicesPreview: { eyebrow: 'Nos services', title: 'Nos services', intro: "Trois manières de connecter vos équipes à l'IA — de la formation à l'implémentation." },
    services: [
      { icon: 'graduation-cap', title: 'Formation IA',
        tagline: "Former vos équipes à travailler avec l'IA",
        desc: "Des programmes de formation sur mesure pour chaque niveau de votre organisation — dirigeants, gestionnaires, employés. Initiations à l'IA, ateliers pratiques, formations aux outils. Nous construisons le plan adapté à votre contexte et à vos objectifs.",
        items: ["Introduction à l'IA", 'Outils IA pratiques', 'Ateliers sur mesure', 'Formation pour dirigeants', 'Formation pour gestionnaires', 'Formation pour employés'] },
      { icon: 'scan-search', title: 'Diagnostic organisationnel',
        tagline: "Identifier où l'IA peut vraiment faire la différence",
        desc: "Nous nous asseyons avec vous, observons vos processus de bout en bout, et identifions les opportunités concrètes d'automatisation et d'intégration IA. Vous repartez avec des recommandations personnalisées : outils adaptés, idées de transformation, plan de formation et feuille de route.",
        items: ['Cartographie des processus', "Opportunités d'automatisation", "Recommandations d'outils IA", 'Plan de formation', 'Feuille de route stratégique', 'Recommandations opérationnelles'] },
      { icon: 'rocket', title: 'Implémentation',
        tagline: 'De la stratégie à la réalité',
        desc: "Au-delà du conseil, nous passons à l'action. Déploiement d'outils d'automatisation, d'agents IA et de systèmes agentiques, exécution des plans de formation, intégration dans vos systèmes existants. Nous exécutons ce que nous recommandons.",
        items: ['Automatisation des processus', 'Agents IA', 'Systèmes agentiques', 'Déploiement de formation', 'Intégration système', 'Accompagnement continu'] },
    ],
    whyUs: {
      eyebrow: 'Notre différence',
      title: 'Pourquoi travailler avec nous ?',
      cards: [
        { title: 'Humain d’abord', desc: "Nous croyons que le succès de l'IA repose sur les personnes, pas sur la technologie. Vos équipes sont toujours au centre." },
        { title: 'Du diagnostic à l’implémentation', desc: "Nous ne nous arrêtons pas aux recommandations. Nous formons, diagnostiquons et déployons — un partenaire complet pour votre transformation IA." },
        { title: 'Personnalisé pour votre réalité', desc: 'Chaque organisation est unique. Nos recommandations d’outils, plans de formation et stratégies sont entièrement adaptés à votre contexte.' },
        { title: 'L’IA comme opportunité', desc: "Dans un monde où l'IA divise, nous aidons vos équipes à voir et à saisir les opportunités — pour croître, innover et créer de nouvelles façons de travailler." },
        { title: 'Expertise multisectorielle', desc: 'Notre équipe multidisciplinaire apporte une expérience concrète dans plusieurs secteurs. Nous comprenons vos enjeux et parlons votre langue.' },
      ],
    },
    methodology: {
      eyebrow: 'Notre approche',
      title: 'Notre approche',
      intro: "Une démarche en quatre temps, de la définition au déploiement concret.",
      steps: [
        { step: '01', title: 'Définir', desc: 'Nous apprenons à connaître votre organisation — vos objectifs, vos processus et vos enjeux humains.' },
        { step: '02', title: 'Diagnostiquer', desc: "Nous identifions les opportunités concrètes d'intégration IA et les zones à fort potentiel d'automatisation." },
        { step: '03', title: 'Développer', desc: "Nous concevons un plan sur mesure — formations, recommandations d'outils et stratégie d'implémentation." },
        { step: '04', title: 'Déployer', desc: "Nous passons à l'action : déploiement des outils, agents IA, automatisations et exécution des formations." },
      ],
    },
    industries: {
      eyebrow: 'Secteurs',
      title: 'Secteurs que nous accompagnons',
      intro: "Une expérience concrète, au service de chaque réalité organisationnelle.",
      list: ['PME', 'Services professionnels', 'Secteur public', 'Éducation', 'Organismes à but non lucratif', 'Opérations industrielles', 'Santé', 'Environnement & Développement durable'],
    },
    about: {
      eyebrow: 'À propos',
      title: 'À propos',
      intro: [
        "Notre mission est de construire le lien entre l'humain et l'intelligence artificielle au sein des organisations.",
        "Nous croyons que l'IA représente une opportunité extraordinaire — pour créer de la valeur, améliorer la productivité et faire émerger de nouveaux rôles. Mais pour y parvenir, il faut plus que de la technologie : il faut des personnes formées, des processus repensés et une stratégie claire.",
        'Grâce à notre équipe multidisciplinaire, nous accompagnons les organisations dans chaque étape — de la formation initiale jusqu’à l’implémentation concrète.',
      ],
      teamTitle: 'Une équipe multidisciplinaire',
      teamBody: "Humexa réunit un réseau multidisciplinaire d'experts en IA, en formation et en transformation organisationnelle.",
      areas: ['Formation IA', 'Diagnostic organisationnel', 'Automatisation des processus', 'Agents & systèmes agentiques', 'Stratégie d’affaires', 'Gestion du changement', 'Transformation numérique', 'Optimisation des processus', 'Leadership exécutif', 'Intégration système'],
      core: "Chaque organisation est unique. Notre force réside dans la combinaison d'une expertise approfondie en IA et d'une connaissance sectorielle étendue, pour connecter vos équipes à l'intelligence artificielle de façon concrète, humaine et durable.",
    },
    insights: {
      eyebrow: 'Perspectives',
      title: 'Perspectives',
      note: 'Contenu exemple — à remplacer.',
      articles: [
        { tag: 'Stratégie', date: 'Mars 2026', title: "Cinq questions à poser avant de connecter vos équipes à l'IA", excerpt: 'Un cadre simple pour évaluer la maturité de votre organisation avant tout projet.' },
        { tag: 'Humain', date: 'Février 2026', title: "Amplifier sans remplacer : repenser le rôle de vos équipes", excerpt: "Comment l'IA crée de nouveaux rôles plutôt que d'en supprimer." },
        { tag: 'Formation', date: 'Janvier 2026', title: "Former les dirigeants à l'ère générative", excerpt: "Ce que chaque comité de direction devrait comprendre de l'IA générative." },
      ],
      readMore: "Lire l'article →",
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Construisons votre pont vers l’IA',
      support: "Prêt à connecter vos équipes à l'intelligence artificielle ? Parlons de votre réalité, de vos défis, et de ce que nous pouvons bâtir ensemble.",
      fields: { name: 'Nom', org: 'Organisation', email: 'Courriel', phone: 'Téléphone', message: 'Message' },
      placeholders: { name: 'Votre nom', org: 'Votre organisation', email: 'vous@exemple.com', phone: '+1 …', message: 'Votre message' },
      submit: 'Planifier une rencontre',
      success: 'Merci — nous vous répondrons sous peu.',
      errRequired: 'Ce champ est requis.',
      errEmail: 'Adresse courriel invalide.',
    },
    statement: "Humexa construit le lien entre vos équipes et l'intelligence artificielle — à travers la formation, le diagnostic organisationnel et l'implémentation.",
    finalCta: { title: 'Construisons votre pont vers l’IA', sub: "Planifions une première rencontre pour explorer ce que nous pouvons bâtir, ensemble." },
  },

  en: {
    brand: 'Humexa',
    cta: 'Schedule a Meeting',
    nav: [
      { id: 'services', label: 'Services' },
      { id: 'approche', label: 'Approach' },
      { id: 'industries', label: 'Industries' },
      { id: 'apropos', label: 'About' },
      { id: 'perspectives', label: 'Insights' },
    ],
    hero: {
      eyebrow: 'Human ↔ AI',
      title: 'AI transformation built around people',
      sub: "AI isn't here to replace your teams. It's here to amplify them. We build the connection between your people and artificial intelligence — through training, diagnostics, and implementation — so every person in your organization can fully benefit from it.",
      primary: 'Get Started',
      ghost: 'Discover Our Services',
    },
    why: {
      eyebrow: 'Why now',
      title: 'Why Human ↔ AI?',
      body: 'AI shouldn’t be feared. It should create opportunities. Organizations that thrive aren’t those that replaced their teams — they’re those that connected their people to artificial intelligence: to automate repetitive tasks, make better decisions, and create new roles. The question is no longer “should we adopt AI?” — it’s “how do we make it work with your teams?”',
    },
    servicesPreview: { eyebrow: 'Our services', title: 'Our Services', intro: 'Three ways to connect your teams to AI — from training to implementation.' },
    services: [
      { icon: 'graduation-cap', title: 'AI Training',
        tagline: 'Equip your teams to work with AI',
        desc: 'Custom training programs for every level of your organization — executives, managers, employees. AI fundamentals, hands-on workshops, tool-specific training. We build the program that fits your context and your goals.',
        items: ['AI Fundamentals', 'Practical AI Tools', 'Custom Workshops', 'Executive Training', 'Manager Training', 'Employee Training'] },
      { icon: 'scan-search', title: 'Organizational Diagnostic',
        tagline: 'Identify where AI can make a real difference',
        desc: 'We sit with you, observe your end-to-end processes, and identify concrete automation and AI integration opportunities. You leave with personalized recommendations: adapted tools, transformation ideas, training plan, and a roadmap.',
        items: ['Process Mapping', 'Automation Opportunities', 'AI Tool Recommendations', 'Training Plan', 'Strategic Roadmap', 'Operational Recommendations'] },
      { icon: 'rocket', title: 'Implementation',
        tagline: 'From Strategy to Reality',
        desc: 'Beyond consulting, we execute. Deploying automation tools, AI agents, and agentic systems, running training programs, integrating into your existing systems. We implement what we recommend.',
        items: ['Process Automation', 'AI Agents', 'Agentic Systems', 'Training Deployment', 'System Integration', 'Ongoing Support'] },
    ],
    whyUs: {
      eyebrow: 'Our difference',
      title: 'Why Work With Us?',
      cards: [
        { title: 'Human-First', desc: 'We believe AI success is built on people, not technology. Your teams are always at the center.' },
        { title: 'From Diagnosis to Deployment', desc: 'We don’t stop at recommendations. We train, diagnose, and deploy — a complete partner for your AI transformation.' },
        { title: 'Tailored to Your Reality', desc: 'Every organization is unique. Our tool recommendations, training plans, and strategies are fully tailored to your context.' },
        { title: 'AI as Opportunity', desc: 'In a world where AI divides, we help your teams see and seize the opportunities — to grow, innovate, and create new ways of working.' },
        { title: 'Multi-Sector Expertise', desc: 'Our multidisciplinary team brings concrete experience across multiple sectors. We understand your challenges and speak your language.' },
      ],
    },
    methodology: {
      eyebrow: 'Our approach',
      title: 'Our Approach',
      intro: 'A four-step journey, from definition to concrete deployment.',
      steps: [
        { step: '01', title: 'Define', desc: 'We get to know your organization — your goals, your processes, and your people.' },
        { step: '02', title: 'Diagnose', desc: 'We identify concrete AI integration opportunities and areas with high automation potential.' },
        { step: '03', title: 'Develop', desc: 'We build a tailored plan — training programs, tool recommendations, and implementation strategy.' },
        { step: '04', title: 'Deploy', desc: 'We execute: deploying tools, AI agents, automations, and running training programs.' },
      ],
    },
    industries: {
      eyebrow: 'Sectors',
      title: 'Industries We Serve',
      intro: 'Concrete experience, in service of every organizational reality.',
      list: ['SMEs', 'Professional Services', 'Public Sector', 'Education', 'Non-Profit Organizations', 'Industrial Operations', 'Healthcare', 'Environment & Sustainability'],
    },
    about: {
      eyebrow: 'About',
      title: 'About',
      intro: [
        'Our mission is to build the connection between humans and artificial intelligence within organizations.',
        'We believe AI represents an extraordinary opportunity — to create value, improve productivity, and give rise to new roles. But to get there, you need more than technology: you need trained people, rethought processes, and a clear strategy.',
        'With our multidisciplinary team, we guide organizations through every stage — from initial training to concrete implementation.',
      ],
      teamTitle: 'A Multidisciplinary Team',
      teamBody: 'Humexa brings together a multidisciplinary network of experts in AI, training, and organizational transformation.',
      areas: ['AI Training', 'Organizational Diagnostic', 'Process Automation', 'Agents & Agentic Systems', 'Business Strategy', 'Change Management', 'Digital Transformation', 'Process Optimization', 'Executive Leadership', 'System Integration'],
      core: 'Every organization is unique. Our strength lies in combining deep AI expertise with broad sector knowledge — to connect your teams to artificial intelligence in a way that is concrete, human, and durable.',
    },
    insights: {
      eyebrow: 'Insights',
      title: 'Insights',
      note: 'Sample content — to be replaced.',
      articles: [
        { tag: 'Strategy', date: 'March 2026', title: 'Five questions to ask before connecting your teams to AI', excerpt: 'A simple framework to assess your organization’s maturity before any project.' },
        { tag: 'People', date: 'February 2026', title: 'Amplify, don’t replace: rethinking your team’s role', excerpt: 'How AI creates new roles rather than removing them.' },
        { tag: 'Training', date: 'January 2026', title: 'Training leaders for the generative era', excerpt: 'What every leadership team should understand about generative AI.' },
      ],
      readMore: 'Read the article →',
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Let’s Build Your Bridge to AI',
      support: 'Ready to connect your teams to AI? Let’s talk about your reality, your challenges, and what we can build together.',
      fields: { name: 'Name', org: 'Organization', email: 'Email', phone: 'Phone', message: 'Message' },
      placeholders: { name: 'Your name', org: 'Your organization', email: 'you@example.com', phone: '+1 …', message: 'Your message' },
      submit: 'Schedule a Meeting',
      success: 'Thank you — we’ll be in touch shortly.',
      errRequired: 'This field is required.',
      errEmail: 'Invalid email address.',
    },
    statement: 'Humexa builds the connection between your teams and AI — through training, organizational diagnostics, and implementation.',
    finalCta: { title: 'Let’s Build Your Bridge to AI', sub: 'Let’s schedule a first meeting to explore what we can build, together.' },
  },
};
