/* Bilingual copy for the Saventia marketing site (verbatim from the brief). */
window.SITE_CONTENT = {
  fr: {
    brand: 'Saventia',
    cta: 'Planifier une rencontre',
    nav: [
      { id: 'services', label: 'Services' },
      { id: 'approche', label: 'Approche' },
      { id: 'industries', label: 'Industries' },
      { id: 'apropos', label: 'À propos' },
      { id: 'perspectives', label: 'Perspectives' },
    ],
    hero: {
      eyebrow: 'Intelligence artificielle organisationnelle',
      title: "L'intelligence artificielle pensée pour les organisations",
      sub: "Nous accompagnons les entreprises et les institutions dans l'intégration stratégique de l'intelligence artificielle grâce à une approche multidisciplinaire combinant expertise technologique, connaissance sectorielle et transformation organisationnelle.",
      primary: 'Planifier une rencontre',
      ghost: 'Découvrir nos services',
    },
    why: {
      eyebrow: 'Pourquoi maintenant',
      title: "Pourquoi l'IA organisationnelle ?",
      body: "L'intelligence artificielle ne se limite pas à la technologie. Son véritable potentiel réside dans sa capacité à améliorer les processus, soutenir la prise de décision, accroître la productivité et favoriser l'innovation au sein des organisations. Une adoption réussie exige une compréhension des enjeux humains, opérationnels et stratégiques. Nous aidons les organisations à transformer l'IA en avantage concret.",
    },
    servicesPreview: { eyebrow: 'Nos services', title: 'Nos services', intro: "Trois manières d'accompagner votre transformation." },
    services: [
      { icon: 'graduation-cap', title: 'Formation exécutive en intelligence artificielle',
        desc: "Former les dirigeants, gestionnaires et décideurs afin qu'ils puissent comprendre les enjeux, les opportunités et les impacts stratégiques de l'intelligence artificielle.",
        items: ["Introduction à l'IA", 'IA générative', "Opportunités d'affaires", "Gouvernance de l'IA", 'Gestion des risques', 'Leadership en transformation numérique', 'Stratégie IA'] },
      { icon: 'scan-search', title: 'Diagnostic organisationnel et opportunités IA',
        desc: "Analyser les processus, identifier les inefficacités et repérer les opportunités à forte valeur ajoutée pour l'intégration de l'intelligence artificielle.",
        items: ['Cartographie des processus', "Identification des goulots d'étranglement", "Analyse du potentiel d'automatisation", "Cas d'usage prioritaires", 'Feuille de route stratégique', 'Recommandations opérationnelles'] },
      { icon: 'users', title: "Ateliers de sensibilisation à l'intelligence artificielle",
        desc: "Des ateliers interactifs conçus pour démystifier l'IA et mobiliser les équipes autour des opportunités de transformation.",
        items: ["Comprendre l'IA simplement", 'IA générative au travail', 'Impact sur les professions', 'IA responsable et éthique', 'Gestion du changement', 'Futur du travail'] },
    ],
    whyUs: {
      eyebrow: 'Notre différence',
      title: 'Pourquoi travailler avec nous ?',
      cards: [
        { title: 'Une approche multidisciplinaire', desc: 'Nous combinons expertise technologique, vision stratégique et compréhension organisationnelle.' },
        { title: 'Une expertise sectorielle diversifiée', desc: "Notre équipe possède une expérience concrète dans plusieurs secteurs d'activité." },
        { title: 'Une approche concrète et pragmatique', desc: 'Nous privilégions des recommandations applicables et des résultats mesurables.' },
        { title: "Une vision humaine de l'IA", desc: 'Nous plaçons les personnes et les organisations au centre de la transformation.' },
        { title: 'Une IA adaptée à votre réalité', desc: 'Chaque organisation est unique. Nos approches sont personnalisées selon votre contexte, vos objectifs et votre maturité numérique.' },
      ],
    },
    methodology: {
      eyebrow: 'Notre approche',
      title: 'Notre approche',
      intro: "Une démarche en quatre temps, du diagnostic à la transformation durable.",
      steps: [
        { step: '01', title: 'Comprendre', desc: 'Analyser votre organisation, vos objectifs stratégiques et vos enjeux opérationnels.' },
        { step: '02', title: 'Diagnostiquer', desc: "Identifier les opportunités à forte valeur ajoutée pour l'intégration de l'intelligence artificielle." },
        { step: '03', title: 'Former', desc: 'Développer les connaissances et les capacités internes nécessaires à une adoption durable.' },
        { step: '04', title: 'Transformer', desc: 'Mettre en œuvre une feuille de route réaliste et adaptée à votre organisation.' },
      ],
    },
    industries: {
      eyebrow: 'Secteurs',
      title: 'Industries que nous servons',
      intro: "Une connaissance sectorielle approfondie, au service de solutions réalistes.",
      list: ['Télécommunications', 'Fabrication', 'Opérations industrielles', 'PME', 'Services professionnels', 'Secteur public', "Établissements d'enseignement", 'Organismes à but non lucratif'],
    },
    about: {
      eyebrow: 'À propos',
      title: 'À propos',
      intro: [
        "Notre mission est d'aider les organisations à intégrer l'intelligence artificielle de manière stratégique, responsable et durable.",
        "Nous croyons que la réussite de l'IA repose autant sur les personnes, les processus et la gouvernance que sur la technologie elle-même.",
        'Grâce à notre équipe multidisciplinaire, nous accompagnons les organisations dans toutes les étapes de leur transformation.',
      ],
      teamTitle: 'Une équipe multidisciplinaire',
      teamBody: "La firme réunit un réseau multidisciplinaire d'experts en IA et en transformation organisationnelle.",
      areas: ['Télécommunications', 'Systèmes industriels', 'Fabrication', 'PME', 'Entrepreneuriat', 'Gestion des opérations', "Stratégie d'affaires", "Gestion de l'innovation", 'Transformation numérique', 'Optimisation des processus', 'Leadership exécutif'],
      core: "L'intelligence artificielle n'est pas universelle. Chaque industrie fait face à des défis et des opportunités uniques. Notre force réside dans la combinaison d'une expertise approfondie en IA et d'une connaissance sectorielle étendue pour offrir des solutions pratiques et réalistes, adaptées à la réalité de chaque organisation.",
    },
    insights: {
      eyebrow: 'Perspectives',
      title: 'Perspectives',
      note: 'Contenu exemple — à remplacer.',
      articles: [
        { tag: 'Stratégie', date: 'Mars 2026', title: "Cinq questions à poser avant d'adopter l'IA", excerpt: 'Un cadre simple pour évaluer la maturité de votre organisation avant tout projet.' },
        { tag: 'Gouvernance', date: 'Février 2026', title: "Gouverner l'IA sans freiner l'innovation", excerpt: "Les principes d'une gouvernance qui protège sans paralyser." },
        { tag: 'Formation', date: 'Janvier 2026', title: "Former les dirigeants à l'ère générative", excerpt: "Ce que chaque comité de direction devrait comprendre de l'IA générative." },
      ],
      readMore: "Lire l'article →",
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Parlons de votre transformation IA',
      support: "Découvrez comment l'intelligence artificielle peut créer de la valeur dans votre organisation.",
      fields: { name: 'Nom', org: 'Organisation', email: 'Courriel', phone: 'Téléphone', message: 'Message' },
      placeholders: { name: 'Votre nom', org: 'Votre organisation', email: 'vous@exemple.com', phone: '+1 …', message: 'Votre message' },
      submit: 'Planifier une rencontre',
      success: 'Merci — nous vous répondrons sous peu.',
      errRequired: 'Ce champ est requis.',
      errEmail: 'Adresse courriel invalide.',
    },
    statement: "Nous aidons les organisations à comprendre, adopter et intégrer l'intelligence artificielle grâce à une approche multidisciplinaire combinant expertise technologique, transformation organisationnelle et connaissance sectorielle.",
    finalCta: { title: 'Prêt à transformer votre organisation ?', sub: "Planifions une première rencontre pour explorer le potentiel de l'IA dans votre contexte." },
  },

  en: {
    brand: 'Saventia',
    cta: 'Schedule a Meeting',
    nav: [
      { id: 'services', label: 'Services' },
      { id: 'approche', label: 'Approach' },
      { id: 'industries', label: 'Industries' },
      { id: 'apropos', label: 'About' },
      { id: 'perspectives', label: 'Insights' },
    ],
    hero: {
      eyebrow: 'Organizational Artificial Intelligence',
      title: 'Artificial Intelligence built for organizations',
      sub: 'We support organizations and institutions in strategically integrating artificial intelligence through a multidisciplinary approach combining technological expertise, sector knowledge, and organizational transformation.',
      primary: 'Schedule a Meeting',
      ghost: 'Discover Our Services',
    },
    why: {
      eyebrow: 'Why now',
      title: 'Why AI for organizations?',
      body: 'Artificial intelligence is not limited to technology. Its real potential lies in its ability to improve processes, support decision-making, increase productivity, and foster innovation within organizations. Successful adoption requires understanding human, operational, and strategic stakes. We help organizations turn AI into concrete advantage.',
    },
    servicesPreview: { eyebrow: 'Our services', title: 'Our services', intro: 'Three ways to support your transformation.' },
    services: [
      { icon: 'graduation-cap', title: 'Executive AI Training',
        desc: 'Train leaders, managers, and decision-makers so they can understand the strategic stakes, opportunities, and impacts of artificial intelligence.',
        items: ['Introduction to AI', 'Generative AI', 'Business opportunities', 'AI governance', 'Risk management', 'Digital transformation leadership', 'AI strategy'] },
      { icon: 'scan-search', title: 'Organizational Diagnostic & AI Opportunities',
        desc: 'Analyze processes, identify inefficiencies, and spot high-value opportunities for integrating artificial intelligence.',
        items: ['Process mapping', 'Bottleneck identification', 'Automation potential analysis', 'Priority use cases', 'Strategic roadmap', 'Operational recommendations'] },
      { icon: 'users', title: 'AI Awareness Workshops',
        desc: 'Interactive workshops designed to demystify AI and mobilize teams around transformation opportunities.',
        items: ['Understanding AI simply', 'Generative AI at work', 'Impact on professions', 'Responsible & ethical AI', 'Change management', 'Future of work'] },
    ],
    whyUs: {
      eyebrow: 'Our difference',
      title: 'Why work with us?',
      cards: [
        { title: 'A multidisciplinary approach', desc: 'We combine technological expertise, strategic vision, and organizational understanding.' },
        { title: 'Diverse sector expertise', desc: 'Our team has concrete experience across many industries.' },
        { title: 'A concrete, pragmatic approach', desc: 'We prioritize actionable recommendations and measurable results.' },
        { title: 'A human vision of AI', desc: 'We place people and organizations at the center of transformation.' },
        { title: 'AI adapted to your reality', desc: 'Every organization is unique. Our approaches are tailored to your context, goals, and digital maturity.' },
      ],
    },
    methodology: {
      eyebrow: 'Our approach',
      title: 'Our approach',
      intro: 'A four-step journey, from diagnostic to durable transformation.',
      steps: [
        { step: '01', title: 'Understand', desc: 'Analyze your organization, strategic goals, and operational challenges.' },
        { step: '02', title: 'Diagnose', desc: 'Identify high-value opportunities for integrating artificial intelligence.' },
        { step: '03', title: 'Train', desc: 'Build the internal knowledge and capabilities needed for durable adoption.' },
        { step: '04', title: 'Transform', desc: 'Implement a realistic roadmap tailored to your organization.' },
      ],
    },
    industries: {
      eyebrow: 'Sectors',
      title: 'Industries We Serve',
      intro: 'Deep sector knowledge, in service of realistic solutions.',
      list: ['Telecommunications', 'Manufacturing', 'Industrial Operations', 'SMEs', 'Professional Services', 'Public Sector', 'Educational Institutions', 'Non-Profit Organizations'],
    },
    about: {
      eyebrow: 'About',
      title: 'About us',
      intro: [
        'Our mission is to help organizations integrate artificial intelligence in a strategic, responsible, and sustainable way.',
        'We believe AI success rests as much on people, processes, and governance as on the technology itself.',
        'Through our multidisciplinary team, we support organizations at every step of their transformation.',
      ],
      teamTitle: 'A Multidisciplinary Team',
      teamBody: 'The firm brings together a multidisciplinary network of experts in AI and organizational transformation.',
      areas: ['Telecommunications', 'Industrial systems', 'Manufacturing', 'SMEs', 'Entrepreneurship', 'Operations management', 'Business strategy', 'Innovation management', 'Digital transformation', 'Process optimization', 'Executive leadership'],
      core: 'Artificial intelligence is not universal. Each industry faces unique challenges and opportunities. Our strength lies in combining deep AI expertise with broad sector knowledge to deliver practical, realistic solutions tailored to each organization\u2019s reality.',
    },
    insights: {
      eyebrow: 'Insights',
      title: 'Insights',
      note: 'Sample content — to be replaced.',
      articles: [
        { tag: 'Strategy', date: 'March 2026', title: 'Five questions to ask before adopting AI', excerpt: 'A simple framework to assess your organization\u2019s maturity before any project.' },
        { tag: 'Governance', date: 'February 2026', title: 'Governing AI without stifling innovation', excerpt: 'The principles of governance that protects without paralyzing.' },
        { tag: 'Training', date: 'January 2026', title: 'Training leaders for the generative era', excerpt: 'What every leadership team should understand about generative AI.' },
      ],
      readMore: 'Read the article →',
    },
    contact: {
      eyebrow: 'Contact',
      title: "Let's talk about your AI transformation",
      support: 'Discover how artificial intelligence can create value in your organization.',
      fields: { name: 'Name', org: 'Organization', email: 'Email', phone: 'Phone', message: 'Message' },
      placeholders: { name: 'Your name', org: 'Your organization', email: 'you@example.com', phone: '+1 …', message: 'Your message' },
      submit: 'Schedule a Meeting',
      success: 'Thank you — we\u2019ll be in touch shortly.',
      errRequired: 'This field is required.',
      errEmail: 'Invalid email address.',
    },
    statement: 'We help organizations understand, adopt, and integrate artificial intelligence through a multidisciplinary approach combining technological expertise, organizational transformation, and sector-specific knowledge.',
    finalCta: { title: 'Ready to transform your organization?', sub: "Let's schedule a first meeting to explore the potential of AI in your context." },
  },
};
